- hosts: win
  tasks:
  - name: Stop Process
    win_shell: |
            Stop-Process -Id "{{id}}"
            Get-Process | Where-Object {$_.HasExited}

    register: command_output

  - name: out
    debug:
      var: command_output.stdout_lines



ansible@ip-172-31-95-198:~$ sudo vi idstop.yaml
ansible@ip-172-31-95-198:~$ ansible-playbook idstop.yaml --extra-var id=6640

PLAY [win] **********************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [18.233.171.244]

TASK [Stop Process] *************************************************************************************************************************************************************************
changed: [18.233.171.244]

TASK [out] **********************************************************************************************************************************************************************************
ok: [18.233.171.244] => {
    "command_output.stdout_lines": [
        "",
        "Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                  ",
        "-------  ------    -----      -----     ------     --  -- -----------                                                  ",
        "    113       7     1660        360       0.02   6640   3 git-bash                                                     ",
        "",
